#!/bin/bash
# SpecSwarm Preflight Check: ground-truth-bias (v7.16.0 — AUTO-MAGIC WS8)
#
# When a plan evaluates or tunes against user-acceptance / ground-truth data,
# WARN unless the plan states the provenance of that data (segmenting or
# excluding items generated by the system under evaluation).
#
# Origin lesson: 22 of 26 "user-accepted" items in a production eval were the
# scorer's OWN prior suggestions (interface gravity) — tuning to them would
# have been the scorer grading its own homework. The eval must segment or
# exclude self-generated ground truth.
#
# Severity model:
#   - no eval-against-acceptance language in plan.md → PASS-skip (guard not
#     applicable; this is a conditional guard, not an extractor, so the
#     WARN-on-zero rule does not apply)
#   - eval language present + provenance/segmentation language present → PASS
#   - eval language present, no provenance note → WARN (judgment-heavy; never
#     blocks — it asks the question a human forgot to ask)
#
# Input:  $1 = absolute path to plan.md
# Output: First line "PASS|WARN|FAIL <summary>", then indented details.

set -e

PLAN_PATH="${1:-}"
if [ -z "$PLAN_PATH" ] || [ ! -f "$PLAN_PATH" ]; then
  echo "FAIL ground-truth-bias: plan path missing or not found ($PLAN_PATH)"
  exit 2
fi

EVAL_RE='(ground.?truth|acceptance (data|rate|set)|user.accepted|accepted (items|suggestions|outputs)|tune.* (against|to)|calibrat.* against)'
PROVENANCE_RE='(self.generated|interface gravity|segment(ed|ing)? .*(ground.?truth|acceptance|self)|exclud(e|ed|ing) .*(self|own|generated)|provenance)'

EVAL_HITS=$(grep -inE "$EVAL_RE" "$PLAN_PATH" 2>/dev/null || true)

if [ -z "$EVAL_HITS" ]; then
  echo "PASS ground-truth-bias: skipped (plan does not evaluate against acceptance/ground-truth data)"
  exit 0
fi

if grep -qiE "$PROVENANCE_RE" "$PLAN_PATH" 2>/dev/null; then
  COUNT=$(echo "$EVAL_HITS" | wc -l)
  echo "PASS ground-truth-bias: ${COUNT} eval-against-acceptance mention(s), provenance/segmentation is addressed"
  exit 0
fi

COUNT=$(echo "$EVAL_HITS" | wc -l)
echo "WARN ground-truth-bias: plan evaluates against acceptance/ground-truth data with NO provenance note — were the acceptances generated by the system under evaluation?"
echo "$EVAL_HITS" | head -n 5 | while IFS=: read -r lineno rest; do
  echo "  ⚠️  line ${lineno}: $(echo "$rest" | head -c 100)"
done
echo "  Require the eval to segment or exclude self-generated ground truth (interface gravity)."
echo "  Origin: 22/26 'user-accepted' items in production were the scorer's own suggestions."
exit 1
