#!/bin/bash
# Generated by cc-statusline v1.3.2 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2025-11-03T17:44:44.045Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, session, tokens, burnrate
STATUSLINE_VERSION="1.3.2"

input=$(cat)

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- logging ----
{
  echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
  echo "[$TIMESTAMP] Input:"
  if [ "$HAS_JQ" -eq 1 ]; then
    echo "$input" | jq . 2>/dev/null || echo "$input"
    echo "[$TIMESTAMP] Using jq for JSON parsing"
  else
    echo "$input"
    echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
  fi
  echo "---"
} >> "$LOG_FILE" 2>/dev/null

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
worktree_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; } # peach/orange
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# effort level color (dynamic based on level)
effort_color() {
  if [ "$use_color" -eq 1 ]; then
    case "$effort_level" in
      low)    printf '\033[38;5;117m' ;;  # sky blue
      medium) printf '\033[38;5;222m' ;;  # light gold
      high)   printf '\033[38;5;203m' ;;  # coral red
      *)      printf '\033[38;5;249m' ;;  # light gray
    esac
  fi
}

# rate limit color (parameterized by percentage)
rate_limit_color() {
  local pct="${1:-0}"
  if [ "$use_color" -eq 1 ]; then
    if [ "$pct" -gt 80 ]; then
      printf '\033[38;5;203m'   # coral red (>80%)
    elif [ "$pct" -gt 50 ]; then
      printf '\033[38;5;222m'   # light gold (50-80%)
    else
      printf '\033[38;5;158m'   # mint green (<50%)
    fi
  fi
}

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- effort level ----
effort_level=""
SETTINGS_FILE="$HOME/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
  if [ "$HAS_JQ" -eq 1 ]; then
    effort_level=$(jq -r '.effortLevel // empty' "$SETTINGS_FILE" 2>/dev/null)
  else
    effort_level=$(grep -o '"effortLevel"[[:space:]]*:[[:space:]]*"[^"]*"' "$SETTINGS_FILE" | sed 's/.*"\([^"]*\)"$/\1/')
  fi
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
is_worktree=0
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
  # Worktree detection: if git-dir differs from git-common-dir, we're in a worktree
  wt_git_dir=$(git rev-parse --git-dir 2>/dev/null)
  wt_common_dir=$(git rev-parse --git-common-dir 2>/dev/null)
  if [ -n "$wt_git_dir" ] && [ -n "$wt_common_dir" ] && [ "$wt_git_dir" != "$wt_common_dir" ]; then
    is_worktree=1
  fi
fi

# ---- context window (from JSON input) ----
ctx_used_pct=""
ctx_remaining_pct=""
ctx_window_size=""
ctx_bar=""

if [ "$HAS_JQ" -eq 1 ]; then
  ctx_used_pct=$(echo "$input" | jq -r '.context_window.used_percentage // empty' 2>/dev/null)
  ctx_remaining_pct=$(echo "$input" | jq -r '.context_window.remaining_percentage // empty' 2>/dev/null)
  ctx_window_size=$(echo "$input" | jq -r '.context_window.context_window_size // empty' 2>/dev/null)
else
  ctx_used_pct=$(echo "$input" | grep -o '"used_percentage"[[:space:]]*:[[:space:]]*[0-9]*' | head -1 | grep -o '[0-9]*$')
  ctx_remaining_pct=$(echo "$input" | grep -o '"remaining_percentage"[[:space:]]*:[[:space:]]*[0-9]*' | head -1 | grep -o '[0-9]*$')
  ctx_window_size=$(echo "$input" | grep -o '"context_window_size"[[:space:]]*:[[:space:]]*[0-9]*' | head -1 | grep -o '[0-9]*$')
fi

# Color based on usage (higher = worse)
context_color() {
  if [ "$use_color" -eq 1 ]; then
    local pct="${ctx_used_pct:-0}"
    if [ "$pct" -gt 75 ]; then
      printf '\033[38;5;203m'   # coral red (>75%)
    elif [ "$pct" -gt 50 ]; then
      printf '\033[38;5;215m'   # peach (50-75%)
    else
      printf '\033[38;5;158m'   # mint green (<50%)
    fi
  fi
}

# Format window size label (e.g. 1000000 -> 1M, 200000 -> 200K)
ctx_size_label=""
if [ -n "$ctx_window_size" ] && [[ "$ctx_window_size" =~ ^[0-9]+$ ]]; then
  if [ "$ctx_window_size" -ge 1000000 ]; then
    ctx_size_label=" $(( ctx_window_size / 1000000 ))M"
  elif [ "$ctx_window_size" -ge 1000 ]; then
    ctx_size_label=" $(( ctx_window_size / 1000 ))K"
  fi
fi

# ---- usage colors ----
usage_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;189m'; fi; }  # lavender
cost_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # light gold
burn_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;220m'; fi; }   # bright gold
session_color() { 
  rem_pct=$(( 100 - session_pct ))
  if   (( rem_pct <= 10 )); then SCLR='38;5;210'  # light pink
  elif (( rem_pct <= 25 )); then SCLR='38;5;228'  # light yellow  
  else                          SCLR='38;5;194'; fi  # light green
  if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$SCLR"; fi
}

# ---- cost and usage extraction ----
session_txt=""; session_pct=0; session_bar=""
cost_usd=""; cost_per_hour=""; tpm=""; tot_tokens=""

# Extract cost data from Claude Code input
if [ "$HAS_JQ" -eq 1 ]; then
  # Get cost data from Claude Code's input
  cost_usd=$(echo "$input" | jq -r '.cost.total_cost_usd // empty' 2>/dev/null)
  total_duration_ms=$(echo "$input" | jq -r '.cost.total_duration_ms // empty' 2>/dev/null)
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
else
  # Bash fallback for cost extraction
  cost_usd=$(echo "$input" | grep -o '"total_cost_usd"[[:space:]]*:[[:space:]]*[0-9.]*' | sed 's/.*:[[:space:]]*\([0-9.]*\).*/\1/')
  total_duration_ms=$(echo "$input" | grep -o '"total_duration_ms"[[:space:]]*:[[:space:]]*[0-9]*' | sed 's/.*:[[:space:]]*\([0-9]*\).*/\1/')  
  
  # Calculate burn rate ($/hour) from cost and duration
  if [ -n "$cost_usd" ] && [ -n "$total_duration_ms" ] && [ "$total_duration_ms" -gt 0 ]; then
    # Convert ms to hours and calculate rate
    cost_per_hour=$(echo "$cost_usd $total_duration_ms" | awk '{printf "%.2f", $1 * 3600000 / $2}')
  fi
fi

# ---- rate limit extraction ----
rl_5h_pct=""; rl_7d_pct=""
rl_5h_resets=""; rl_7d_resets=""

if [ "$HAS_JQ" -eq 1 ]; then
  rl_5h_pct=$(echo "$input" | jq -r '.rate_limits.five_hour.used_percentage // empty' 2>/dev/null)
  rl_7d_pct=$(echo "$input" | jq -r '.rate_limits.seven_day.used_percentage // empty' 2>/dev/null)
  rl_5h_resets=$(echo "$input" | jq -r '.rate_limits.five_hour.resets_at // empty' 2>/dev/null)
  rl_7d_resets=$(echo "$input" | jq -r '.rate_limits.seven_day.resets_at // empty' 2>/dev/null)
else
  rl_5h_pct=$(echo "$input" | grep -o '"five_hour"[^}]*"used_percentage"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
  rl_7d_pct=$(echo "$input" | grep -o '"seven_day"[^}]*"used_percentage"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
  rl_5h_resets=$(echo "$input" | grep -o '"five_hour"[^}]*"resets_at"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
  rl_7d_resets=$(echo "$input" | grep -o '"seven_day"[^}]*"resets_at"[[:space:]]*:[[:space:]]*[0-9]*' | grep -o '[0-9]*$')
fi

# Truncate floats to integers (API can return values like 14.000000000000002)
[[ "$rl_5h_pct" =~ ^[0-9] ]] && rl_5h_pct=$(printf '%.0f' "$rl_5h_pct")
[[ "$rl_7d_pct" =~ ^[0-9] ]] && rl_7d_pct=$(printf '%.0f' "$rl_7d_pct")

# Format remaining time from epoch timestamp
fmt_reset_time() {
  local epoch="$1"
  local now_sec=$(date +%s)
  local remaining=$(( epoch - now_sec ))
  if [ "$remaining" -le 0 ]; then
    echo "now"
  elif [ "$remaining" -ge 86400 ]; then
    echo "$(( remaining / 86400 ))d$(( (remaining % 86400) / 3600 ))h"
  elif [ "$remaining" -ge 3600 ]; then
    echo "$(( remaining / 3600 ))h$(( (remaining % 3600) / 60 ))m"
  else
    echo "$(( remaining / 60 ))m"
  fi
}

# ---- claude platform status (background-cached, never blocks) ----
PLATFORM_STATUS_CACHE="/tmp/claude-platform-status.json"
PLATFORM_STATUS_MAX_AGE=300

_refresh_platform_status() {
  curl -sf --max-time 5 "https://status.claude.com/api/v2/summary.json" \
    > "${PLATFORM_STATUS_CACHE}.tmp" 2>/dev/null \
    && mv "${PLATFORM_STATUS_CACHE}.tmp" "$PLATFORM_STATUS_CACHE" 2>/dev/null \
    || rm -f "${PLATFORM_STATUS_CACHE}.tmp" 2>/dev/null
}

if command -v curl >/dev/null 2>&1; then
  if [ ! -f "$PLATFORM_STATUS_CACHE" ]; then
    (_refresh_platform_status) &
  else
    _cache_mod=$(stat -c %Y "$PLATFORM_STATUS_CACHE" 2>/dev/null || stat -f %m "$PLATFORM_STATUS_CACHE" 2>/dev/null || echo 0)
    _now=$(date +%s)
    if [ $(( _now - _cache_mod )) -ge $PLATFORM_STATUS_MAX_AGE ]; then
      (_refresh_platform_status) &
    fi
  fi
fi

platform_status_line=""
if [ -f "$PLATFORM_STATUS_CACHE" ] && [ "$HAS_JQ" -eq 1 ]; then
  _indicator=$(jq -r '.status.indicator // "none"' "$PLATFORM_STATUS_CACHE" 2>/dev/null)
  if [ "$_indicator" != "none" ]; then
    _incident=$(jq -r '[.incidents[] | select(.status != "resolved") | .name] | first // ""' "$PLATFORM_STATUS_CACHE" 2>/dev/null)
    _affected=$(jq -r '[.components[] | select(.status != "operational") | .name] | join(", ")' "$PLATFORM_STATUS_CACHE" 2>/dev/null)
    _msg="${_incident:-${_affected}}"
    [ -z "$_msg" ] && _msg="$_indicator"
    _ps_clr=""
    _ps_rst=""
    if [ "$use_color" -eq 1 ]; then
      case "$_indicator" in
        minor)    _ps_clr="$(printf '\033[38;5;222m')" ;;  # gold
        major)    _ps_clr="$(printf '\033[38;5;203m')" ;;  # coral
        critical) _ps_clr="$(printf '\033[38;5;196m')" ;;  # bright red
      esac
      _ps_rst="$(printf '\033[0m')"
    fi
    platform_status_line="⚠ ${_ps_clr}${_msg}${_ps_rst}"
  fi
fi

# Get token data and session info from ccusage if available
if command -v ccusage >/dev/null 2>&1 && [ "$HAS_JQ" -eq 1 ]; then
  blocks_output=""
  
  # Try ccusage with timeout for token data and session info
  if command -v timeout >/dev/null 2>&1; then
    blocks_output=$(timeout 5s ccusage blocks --json 2>/dev/null)
  elif command -v gtimeout >/dev/null 2>&1; then
    # macOS with coreutils installed
    blocks_output=$(gtimeout 5s ccusage blocks --json 2>/dev/null)
  else
    # No timeout available, run directly (ccusage should be fast)
    blocks_output=$(ccusage blocks --json 2>/dev/null)
  fi
  if [ -n "$blocks_output" ]; then
    active_block=$(echo "$blocks_output" | jq -c '.blocks[] | select(.isActive == true)' 2>/dev/null | head -n1)
    if [ -n "$active_block" ]; then
      # Get token count from ccusage
      tot_tokens=$(echo "$active_block" | jq -r '.totalTokens // empty')
      # Get tokens per minute from ccusage
      tpm=$(echo "$active_block" | jq -r '.burnRate.tokensPerMinute // empty')
      
      # Session time calculation from ccusage
      reset_time_str=$(echo "$active_block" | jq -r '.usageLimitResetTime // .endTime // empty')
      start_time_str=$(echo "$active_block" | jq -r '.startTime // empty')
      
      if [ -n "$reset_time_str" ] && [ -n "$start_time_str" ]; then
        start_sec=$(to_epoch "$start_time_str"); end_sec=$(to_epoch "$reset_time_str"); now_sec=$(date +%s)
        total=$(( end_sec - start_sec )); (( total<1 )) && total=1
        elapsed=$(( now_sec - start_sec )); (( elapsed<0 ))&&elapsed=0; (( elapsed>total ))&&elapsed=$total
        session_pct=$(( elapsed * 100 / total ))
        remaining=$(( end_sec - now_sec )); (( remaining<0 )) && remaining=0
        rh=$(( remaining / 3600 )); rm=$(( (remaining % 3600) / 60 ))
        end_hm=$(fmt_time_hm "$end_sec")
        session_txt="$(printf '%dh %dm until reset at %s (%d%%)' "$rh" "$rm" "$end_hm" "$session_pct")"
        session_bar=$(progress_bar "$session_pct" 10)
      fi
    fi
  fi
fi

# ---- terminal width detection (used by prompt truncation + responsive rendering) ----
# Respect COLUMNS env var if set (also useful for testing), otherwise detect from terminal
if [ -n "$COLUMNS" ] && [ "$COLUMNS" -gt 0 ] 2>/dev/null; then
  term_width="$COLUMNS"
elif [ -t 0 ]; then
  term_width=$(tput cols 2>/dev/null || echo 80)
elif [ -t 2 ]; then
  term_width=$(tput cols </dev/tty 2>/dev/null || echo 80)
else
  term_width=$(tput cols </dev/tty 2>/dev/null || echo 80)
fi

# ---- adaptive display helpers ----
# Truncate directory for narrow screens (keep last 2 segments)
adaptive_dir() {
  local dir="$1" max_len="$2"
  if [ "${#dir}" -gt "$max_len" ]; then
    echo "../$(echo "$dir" | rev | cut -d/ -f1-2 | rev)"
  else
    echo "$dir"
  fi
}

# Strip parenthetical from model name on narrow screens
adaptive_model() {
  if [ "$term_width" -lt 80 ]; then
    echo "$1" | sed 's/ (.*//'
  else
    echo "$1"
  fi
}

# Abbreviate effort label on narrow screens
adaptive_effort() {
  if [ "$term_width" -lt 80 ]; then
    case "$1" in
      low) echo "lo" ;; medium) echo "md" ;; high) echo "hi" ;; *) echo "$1" ;;
    esac
  else
    echo "$1"
  fi
}

# Context bar width adapts to terminal
ctx_bar_width() {
  if [ "$term_width" -ge 100 ]; then echo 15
  elif [ "$term_width" -ge 80 ]; then echo 10
  else echo 8; fi
}

# ---- extract last user prompt ----
last_prompt=""
if [ "$HAS_JQ" -eq 1 ]; then
  transcript_path=$(echo "$input" | jq -r '.transcript_path // ""' 2>/dev/null)
  if [ -n "$transcript_path" ] && [ -f "$transcript_path" ]; then
    # Extract last user prompt with string content (actual text prompts)
    # Use tac to reverse the file, find first string-content user message
    full_prompt=$(tac "$transcript_path" 2>/dev/null | grep '"type":"user"' | while IFS= read -r line; do
      content=$(echo "$line" | jq -r 'if (.message.content | type) == "string" then .message.content else empty end' 2>/dev/null)
      if [ -n "$content" ] && [ "$content" != '"' ]; then
        echo "$content"
        break
      fi
    done)

    if [ -n "$full_prompt" ] && [ "$full_prompt" != "null" ]; then
      # Calculate available space for prompt text (term_width already set above)
      # "→ " prefix = 2 chars, "..." suffix = 3 chars, Claude Code right-side UI = 32 chars
      prefix_length=2
      suffix_length=3
      right_margin=32  # Space reserved by Claude Code for "auto-compact: X%" display
      reserved_space=$((prefix_length + suffix_length + right_margin))
      max_prompt_length=$((term_width - reserved_space))

      # Ensure minimum width (prevent negative values on narrow terminals)
      [ "$max_prompt_length" -lt 20 ] && max_prompt_length=20

      # Replace newlines with spaces for single-line display
      full_prompt=$(echo "$full_prompt" | tr '\n' ' ' | sed 's/  */ /g')

      # Strip ANSI codes for accurate length measurement (defensive)
      stripped_prompt=$(echo "$full_prompt" | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g')
      visible_length=${#stripped_prompt}

      # Truncate to fit terminal width
      if [ "$visible_length" -gt "$max_prompt_length" ]; then
        last_prompt=$(echo "$stripped_prompt" | head -c "$max_prompt_length")
        last_prompt="${last_prompt}..."
      else
        last_prompt="$stripped_prompt"
      fi
    fi
  fi
fi

# ---- log extracted data ----
{
  echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, effort=${effort_level:-}, version=${model_version:-}, git=${git_branch:-}, worktree=${is_worktree:-0}, ctx_used=${ctx_used_pct:-}%, ctx_rem=${ctx_remaining_pct:-}%, ctx_size=${ctx_window_size:-}, cost=${cost_usd:-}, cost_ph=${cost_per_hour:-}, tokens=${tot_tokens:-}, tpm=${tpm:-}, session_pct=${session_pct:-}, rl_5h=${rl_5h_pct:-}%, rl_7d=${rl_7d_pct:-}%, last_prompt=${last_prompt:-}"
  if [ "$HAS_JQ" -eq 0 ]; then
    echo "[$TIMESTAMP] Note: Context, tokens, and session info require jq for full functionality"
  fi
} >> "$LOG_FILE" 2>/dev/null

# --- Account email prefix (cached; refreshes when claudeAiOauth.accessToken changes) ---
ACCOUNT_PART=""
ACCOUNT_CACHE="$HOME/.claude/.account-cache"
CREDS_FILE="$HOME/.claude/.credentials.json"

CLAUDE_BIN=$(command -v claude 2>/dev/null || true)
[ -z "$CLAUDE_BIN" ] && [ -x "$HOME/.local/bin/claude" ] && CLAUDE_BIN="$HOME/.local/bin/claude"

CURRENT_AUTH_FP=""
if [ -r "$CREDS_FILE" ]; then
  CURRENT_AUTH_FP=$(jq -r '.claudeAiOauth.accessToken // empty' "$CREDS_FILE" 2>/dev/null \
    | sha1sum 2>/dev/null | cut -c1-16)
fi

CACHED_AUTH_FP=""
if [ -s "$ACCOUNT_CACHE" ]; then
  CACHED_AUTH_FP=$(jq -r '._fp // empty' "$ACCOUNT_CACHE" 2>/dev/null || echo "")
fi

if [ "$CURRENT_AUTH_FP" != "$CACHED_AUTH_FP" ] && [ -n "$CLAUDE_BIN" ]; then
  if STATUS_JSON=$("$CLAUDE_BIN" auth status 2>/dev/null) && [ -n "$STATUS_JSON" ]; then
    echo "$STATUS_JSON" \
      | jq --arg fp "$CURRENT_AUTH_FP" '. + {_fp: $fp}' > "$ACCOUNT_CACHE.tmp" 2>/dev/null
    if [ -s "$ACCOUNT_CACHE.tmp" ]; then
      chmod 600 "$ACCOUNT_CACHE.tmp" 2>/dev/null || true
      mv "$ACCOUNT_CACHE.tmp" "$ACCOUNT_CACHE"
    else
      rm -f "$ACCOUNT_CACHE.tmp"
    fi
  fi
fi

if [ -s "$ACCOUNT_CACHE" ]; then
  EMAIL=$(jq -r '.email // empty' "$ACCOUNT_CACHE" 2>/dev/null || echo "")
  [ -n "$EMAIL" ] && ACCOUNT_PART="${EMAIL%%@*}"
fi

account_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;213m'; fi; }  # bright pink

# ---- render statusline (responsive) ----
# Compute adaptive values based on terminal width
display_dir=$(adaptive_dir "$current_dir" 30)
display_model=$(adaptive_model "$model_name")
display_effort=$(adaptive_effort "$effort_level")
bar_w=$(ctx_bar_width)

# LINE 1: Identity
if [ "$term_width" -lt 80 ]; then
  # Narrow: split into 2 lines (location + model)
  if [ -n "$ACCOUNT_PART" ]; then
    printf '👤 %s%s%s  ' "$(account_color)" "$ACCOUNT_PART" "$(rst)"
  fi
  printf '📁 %s%s%s' "$(dir_color)" "$display_dir" "$(rst)"
  if [ -n "$git_branch" ]; then
    printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
    if [ "$is_worktree" -eq 1 ]; then
      printf ' %s[wt]%s' "$(worktree_color)" "$(rst)"
    fi
  fi
  printf '\n🤖 %s%s%s' "$(model_color)" "$display_model" "$(rst)"
  if [ -n "$display_effort" ]; then
    printf '  ⚡ %s%s%s' "$(effort_color)" "$display_effort" "$(rst)"
  fi
else
  # Medium/Wide: single identity line
  if [ -n "$ACCOUNT_PART" ]; then
    printf '👤 %s%s%s  ' "$(account_color)" "$ACCOUNT_PART" "$(rst)"
  fi
  printf '📁 %s%s%s' "$(dir_color)" "$display_dir" "$(rst)"
  if [ -n "$git_branch" ]; then
    printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
    if [ "$is_worktree" -eq 1 ]; then
      printf ' %s[worktree]%s' "$(worktree_color)" "$(rst)"
    fi
  fi
  printf '  🤖 %s%s%s' "$(model_color)" "$display_model" "$(rst)"
  if [ -n "$display_effort" ]; then
    printf '  ⚡ %s%s%s' "$(effort_color)" "$display_effort" "$(rst)"
  fi
fi

# GAUGES: context bar + rate limits
# On narrow screens, split onto separate lines for readability
line_ctx=""
line_rl=""

# Context bar
if [ -n "$ctx_used_pct" ] && [[ "$ctx_used_pct" =~ ^[0-9]+$ ]]; then
  ctx_bar=$(progress_bar "$ctx_used_pct" "$bar_w")
  size_lbl=""
  [ "$term_width" -ge 80 ] && size_lbl="$ctx_size_label"
  line_ctx="🧠 $(context_color)[${ctx_bar}] ${ctx_used_pct}%${size_lbl}$(rst)"
fi

# Rate limits
if [ -n "$rl_5h_pct" ] && [[ "$rl_5h_pct" =~ ^[0-9]+$ ]]; then
  rl_5h_reset_txt=""
  [ "$term_width" -ge 80 ] && [ -n "$rl_5h_resets" ] && [[ "$rl_5h_resets" =~ ^[0-9]+$ ]] && \
    rl_5h_reset_txt=" ~$(fmt_reset_time "$rl_5h_resets")"
  line_rl="🚦 $(rate_limit_color "$rl_5h_pct")5h:${rl_5h_pct}%${rl_5h_reset_txt}$(rst)"

  if [ -n "$rl_7d_pct" ] && [[ "$rl_7d_pct" =~ ^[0-9]+$ ]]; then
    rl_7d_reset_txt=""
    [ "$term_width" -ge 80 ] && [ -n "$rl_7d_resets" ] && [[ "$rl_7d_resets" =~ ^[0-9]+$ ]] && \
      rl_7d_reset_txt=" ~$(fmt_reset_time "$rl_7d_resets")"
    line_rl="${line_rl}  $(rate_limit_color "$rl_7d_pct")7d:${rl_7d_pct}%${rl_7d_reset_txt}$(rst)"
  fi
fi

# Compose gauges: combined on medium/wide, separate lines on narrow
line2=""
if [ "$term_width" -lt 80 ]; then
  # Narrow: context and rate limits on separate lines
  line2="$line_ctx"
  # Rate limits become line2b (printed separately below)
else
  # Medium/Wide: combined onto one line
  if [ -n "$line_ctx" ] && [ -n "$line_rl" ]; then
    line2="${line_ctx}  ${line_rl}"
  elif [ -n "$line_ctx" ]; then
    line2="$line_ctx"
  elif [ -n "$line_rl" ]; then
    line2="$line_rl"
  fi
fi

# CC version: on wide screens always, on medium only if update available
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  CACHE_FILE="/tmp/claude-version-cache.txt"
  CACHE_MAX_AGE=3600
  version_status=""
  latest_version=""

  if [ -f "$CACHE_FILE" ]; then
    CACHE_TIME=$(stat -c %Y "$CACHE_FILE" 2>/dev/null || stat -f %m "$CACHE_FILE" 2>/dev/null)
    CURRENT_TIME=$(date +%s)
    CACHE_AGE=$((CURRENT_TIME - CACHE_TIME))
    if [ $CACHE_AGE -lt $CACHE_MAX_AGE ]; then
      latest_version=$(cat "$CACHE_FILE" 2>/dev/null)
    else
      (npm view @anthropic-ai/claude-code version 2>/dev/null > "$CACHE_FILE" &)
      latest_version=$(cat "$CACHE_FILE" 2>/dev/null)
    fi
  else
    (npm view @anthropic-ai/claude-code version 2>/dev/null > "$CACHE_FILE" &)
  fi

  # Build version string with color (using printf for proper escape handling)
  ver_colored=""
  if [ -n "$latest_version" ] && [ "$latest_version" != "$cc_version" ]; then
    version_status="update"
    ver_colored="$(printf '\033[38;5;203m')v${cc_version} ⚠ ${latest_version}$(rst)"
  elif [ -n "$latest_version" ]; then
    ver_colored="$(printf '\033[38;5;158m')v${cc_version} ✓$(rst)"
  else
    ver_colored="$(printf '\033[38;5;249m')v${cc_version}$(rst)"
  fi

  # Show on wide always; on medium only if update; hide on narrow
  if [ "$term_width" -ge 100 ]; then
    [ -n "$line2" ] && line2="${line2}  📟 ${ver_colored}" || line2="📟 ${ver_colored}"
  elif [ "$term_width" -ge 80 ] && [ "$version_status" = "update" ]; then
    [ -n "$line2" ] && line2="${line2}  📟 ${ver_colored}" || line2="📟 ${ver_colored}"
  fi
fi

# Append platform status alert to line2 when issues exist
if [ -n "$platform_status_line" ]; then
  [ -n "$line2" ] && line2="${line2}  ${platform_status_line}" || line2="$platform_status_line"
fi

# LINE 3: Session time (from ccusage, conditional)
line3=""
if [ -n "$session_txt" ]; then
  line3="⌛ $(session_color)${session_txt}$(rst) $(session_color)[${session_bar}]$(rst)"
fi

# LINE 4: Token usage (from ccusage, conditional)
line4=""
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    line4="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
  else
    line4="📊 $(usage_color)${tot_tokens} tok$(rst)"
  fi
fi

# LINE 5: Last user prompt (skip on narrow screens)
line5=""
if [ "$term_width" -ge 80 ] && [ -n "$last_prompt" ]; then
  prompt_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;183m'; fi; }  # light mauve
  line5="→ $(prompt_color)${last_prompt}$(rst)"
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
# On narrow screens, rate limits are a separate line
if [ "$term_width" -lt 80 ] && [ -n "$line_rl" ]; then
  printf '\n%s' "$line_rl"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
if [ -n "$line4" ]; then
  printf '\n%s' "$line4"
fi
if [ -n "$line5" ]; then
  printf '\n%s' "$line5"
fi
printf '\n'
